-- 003: hybrid booking (Q-017) — order drafts, human-friendly order number, bargaining floor.
--
-- A "draft" is an order awaiting shopkeeper confirmation (the AI collects it, a human commits it).
-- order_number is what the customer is told (uuid is ugly). min_price is the per-product floor the
-- AI may negotiate down to — internal, never shown to the customer (like boost_level).

alter table public.orders drop constraint if exists orders_status_check;
alter table public.orders add constraint orders_status_check
    check (status in ('draft','pending','confirmed','packed','shipped','delivered','cancelled'));

alter table public.orders
    add column if not exists order_number bigint generated by default as identity;
create unique index if not exists orders_order_number_key on public.orders(order_number);

alter table public.products
    add column if not exists min_price numeric(12,2);  -- AI negotiation floor; null → floor is cost_price

-- Atomic stock decrement (SPEC inventory; Q-017). One conditional UPDATE — the DB, not app code,
-- guarantees two racing confirmations can't oversell the last unit. Returns true iff it decremented.
create or replace function public.decrement_stock(p_id uuid, p_shop uuid, n int)
returns boolean language plpgsql as $$
declare updated int;
begin
    update public.products set quantity = quantity - n
     where id = p_id and shop_id = p_shop and quantity >= n;
    get diagnostics updated = row_count;
    return updated > 0;
end $$;
