-- 004: human-in-the-loop price negotiation (revises ADR-010's secret floor).
--
-- The AI can no longer discount on its own. When a customer haggles (and the shop has
-- negotiation enabled), the AI raises a price_request; a shopkeeper approves/denies/counters it;
-- only an approved price becomes a discount. The old products.min_price floor is removed.

alter table public.shops
    add column if not exists negotiation_enabled boolean not null default true;

create table if not exists public.price_requests (
    id              uuid primary key default gen_random_uuid(),
    request_number  bigint generated by default as identity,
    shop_id         uuid not null references public.shops(id) on delete cascade,
    phone           text not null,
    product_id      uuid not null references public.products(id) on delete cascade,
    requested_price numeric(12,2) not null,
    approved_price  numeric(12,2),
    status          text not null default 'pending' check (status in ('pending','approved','denied')),
    created_at      timestamptz not null default now()
);
create unique index if not exists price_requests_number_key on public.price_requests(request_number);
create index if not exists price_requests_lookup
    on public.price_requests(shop_id, phone, product_id, status);

alter table public.products drop column if exists min_price;  -- floor replaced by explicit approval
