-- 010: friendly IDs (products, riders) + low-stock threshold + counter sales.
--
-- product_number / rider_number: human-readable references (PR0001, rider001) so a shopkeeper can
-- name a product or rider without copying a UUID. Same mechanism as orders.order_number (003) and
-- price_requests.request_number (004): `bigint generated by default as identity` auto-backfills every
-- existing row on ALTER (precedent 003). Global sequence (not per-shop) — matches the existing two.
-- Run a null-count sanity select after applying live (see plan §Flagged 3).
--
-- products.min_qty: low-stock alert threshold. 0 = alerts off (default, no behaviour change). When a
-- confirmed order or counter sale drops quantity to <= min_qty (> 0), the app pings shop + shop owner.
--
-- counter_sales: walk-in sales recorded from a hand-filled sheet photo (shop-owner bot: AI vision
-- extracts rows, human confirms). sold_price is PER UNIT. discrepancy = stock was insufficient when
-- the sale was recorded (durable anti-corruption flag; the row is kept, stock left untouched).

alter table public.products
    add column if not exists product_number bigint generated by default as identity;
create unique index if not exists products_product_number_key on public.products(product_number);

alter table public.delivery_persons
    add column if not exists rider_number bigint generated by default as identity;
create unique index if not exists delivery_persons_rider_number_key on public.delivery_persons(rider_number);

alter table public.products
    add column if not exists min_qty integer not null default 0 check (min_qty >= 0);

create table if not exists public.counter_sales (
    id          uuid primary key default gen_random_uuid(),
    shop_id     uuid not null references public.shops(id) on delete cascade,
    product_id  uuid not null references public.products(id) on delete restrict,
    quantity    integer not null check (quantity > 0),
    sold_price  numeric(12,2) not null check (sold_price >= 0),   -- PER UNIT
    sold_on     date not null,                                    -- Dubai date, set by the app
    photo_path  text,                                             -- proof sheet in shop-media/reports
    recorded_by bigint not null,                                  -- telegram_id of the shop owner
    discrepancy boolean not null default false,                   -- stock insufficient at record time
    created_at  timestamptz not null default now()
);

create index if not exists idx_counter_sales_shop_day on public.counter_sales(shop_id, sold_on desc);

alter table public.counter_sales enable row level security;
create policy "tenant read own shop"  on public.counter_sales for select using (true);
create policy "tenant write own shop" on public.counter_sales for all    using (true) with check (true);
-- ponytail: permissive policies match the repo-wide RLS scaffold (001/008/009); the app layer scopes
-- every query by shop_id. Tighten with the rest when app.shop_id wiring lands.
